[tool.poetry]
name = "neuro"
version = "0.1.0"
description = ""
authors = ["Caio Fontes <caiofontesc@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.44.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
